---
kind: pipeline
name: tests

platform:
  os: linux
  arch: amd64

steps:
  - name: go-tests
    image: golang:1.14.2
    pull: always
    volumes:
    - name: shared
      path: /app
    commands:
      - apt-get update && apt-get install -y npm
      - . .envrc
      - make dependencies ui test
    when:
      event:
        - push

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

volumes:
- name: shared
  temp: {}

steps:
  - name: docker-build
    image: golang:1.14.2
    pull: always
    volumes:
    - name: shared
      path: /app
    commands:
      - apt-get update && apt-get install -y npm
      - . .envrc
      - make dependencies ui build deploy
    when:
      event:
        - push
